name: 'Checkout Lint Build Test'
description: 'Checks out the sources, executes the linting, builds and tests the sources'
runs:
  using: "composite"
  steps:
      - name: Install
        run: npm install
        shell: bash
        working-directory: ./fill-the-box-react
      - name: Lint
        run: npm run lint
        shell: bash
        working-directory: ./fill-the-box-react
      - name: Build
        run: npm run pack
        shell: bash
        working-directory: ./fill-the-box-react
