name: fill-the-box GitHub Tags Actions
on:
  push:
    tags:
      - '**'
jobs:
    release-from-tag:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - id: lint-build-test
          uses: ./.github/actions/lint-build-test
        - uses: octokit/request-action@v2.x
          id: create_release_website
          with:
            route: POST /repos/{owner}/{repo}/releases
            owner: xtoik
            repo: fill-the-box
            name: FillTheBox-React ${{  github.ref_name }}
            tag_name: ${{  github.ref_name }}
            generate_release_notes: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Package Web Site
          run: |
            mv dist fill-the-box-react_${{  github.ref_name }} 
            zip -r fill-the-box-react_${{  github.ref_name }}.zip fill-the-box-react_${{  github.ref_name }}/
            gh release upload ${{  github.ref_name }} fill-the-box-react_${{  github.ref_name }}.zip
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
