name: fill-the-box-react GitHub Push Actions
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - ./fill-the-box-react/**/*
jobs:
    lint-build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - id: checkout-lint-build-test
              uses: ./fill-the-box-react/.github/actions/lint-build-test